[TH2-366] Add description for codec factories and parameters
th2-net/th2-codec-generic pull request #2
Opened 2020-11-23 18:30 UTC by OptimumOpium

2020-11-25 07:40 UTC, jean-michel-perli-sonsin requested changes

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on README.md
> +This repository contains build scripts for general codecs:
This repository contains **the** build scripts for general codecs:

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on README.md
> +The available parameters for each codec you can find in README files in codecs' folders.
**You can find the available parameters for each codec in README files, inside codecs' folders.**

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on README.md
> +If you need to modify some parameters, please, change only parameters you need.
If you need to modify some parameters, please, change only **the** parameters **that** you **will** need.

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on README.md
> +_Do not specify default parameters if you don't want to override them_ (just because it doesn't make any seance to duplicate the configuration).
_Do not specify default parameters if you don't want to override them_ (just because it doesn't make any **sense** to duplicate the configuration).

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-fast/README.md
> +This codec can be used for decoding and encoding message in FAST protocol
This codec can be used for decoding and encoding **messages** in FAST protocol

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-fast/README.md
> +To use the following codec you need to specify the following codec factory:
To use the following codec **,** you **will** need to specify the following codec factory:

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-fix/README.md
> +This codec can be used for decoding and encoding message in FIX protocol
This codec can be used for decoding and encoding **messages** in FIX protocol

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-fix/README.md
> +To use the following codec you need to specify the following codec factory:
To use the **subsequent** codec **,** you **will** need to specify the following codec factory:

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-fix/README.md
> +Configuration example. All parameters have their reasonable default values.
Configuration example. All parameters have their **logical** default values.

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-fix/README.md
> +The name of the decoded messages will be omitted and replaced with `incoming` name.
The name of the decoded messages **which** will be omitted and replaced with **the** `incoming` name.

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-fix/README.md
> +The field converter class that will be used for field conversion if `decodeByDictionary` is disabled. Other converter classes are not available at the moment.
The field converter class that will be used for field conversion, if **the** `decodeByDictionary` is disabled. Other converter classes are not available at the moment.

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-fix/README.md
> +Enables removing trailing zeroes for fields that have `java.lang.Double` and `java.math.BigDecimal` types.
**It enables the removal of** trailing zeroes for fields that have `java.lang.Double` and `java.math.BigDecimal` types.

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-fix/README.md
> +E.g. original value: `100`, value after removing trailing zeroes: `1E+2`
.g. original value: `100`, value after **the removal of** trailing zeroes: `1E+2`

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-itch/README.md
> +This codec can be used for decoding and encoding message in ITCH protocol
This codec can be used for decoding and encoding **messages** in ITCH protocol

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-itch/README.md
> +To use the following codec you need to specify the following codec factory:
To use the **subsequent** codec **,** you need to specify the following codec factory:

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-itch/README.md
> +Configuration example. All parameters have their reasonable default values.
Configuration example. All parameters have their **logical** default values.

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-itch/README.md
> +Specifies the size of the field that contains the length of the following payload (message_header + [**payload_length** + payload] * _n_).
**It specifies** the size of the field **which** contains the length of the following payload (message_header + [**payload_length** + payload] * _n_).

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-ntg/README.md
> +This codec can be used for decoding and encoding message in NTG (Native) protocol.
This codec can be used for decoding and encoding **messages** in NTG (Native) protocol.

2020-11-25 07:40 UTC, jean-michel-perli-sonsin commented on codec-ntg/README.md
> +To use the following codec you need to specify the following codec factory:
To use the **subsequent** codec **,** you **will** need to specify the following codec factory:

2020-11-26 16:02 UTC, jean-michel-perli-sonsin requested changes

2020-11-26 16:02 UTC, jean-michel-perli-sonsin commented on codec-ntg/README.md
> +This codec can be used for decoding and encoding messages in NTG (Native) protocol.
This codec can be used for decoding and encoding messages **via?** NTG (Native) protocol.

2020-11-26 16:02 UTC, jean-michel-perli-sonsin commented on codec-ntg/README.md
> +This codec doesn't have any specific configuration. All decoding/encoding relies on the specified dictionary.
This codec doesn't have any specific configuration. All **the** decoding/encoding relies on the specified dictionary.

2020-11-27 16:16 UTC, Nikita-Smirnov-Exactpro approved these changes

2020-11-27 16:18 UTC, merged