[TH2-4984] Transport protocol support
th2-net/th2-codec-generic pull request #93
Opened 2023-07-18 09:05 UTC by isengrims

2023-07-18 11:26 UTC, Nikita-Smirnov-Exactpro requested changes

2023-07-18 11:26 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +<<<<<<< HEAD
Resolve conflicts

2023-07-18 11:26 UTC, Nikita-Smirnov-Exactpro commented on build.gradle
> +        sailfishVersion               = "3.3.106"
```suggestion
        sailfishVersion               = "3.3.111"
```
use the last release

2023-07-19 10:16 UTC, isengrims commented on build.gradle
> +        sailfishVersion               = "3.3.106"
Done

2023-07-19 10:16 UTC, isengrims commented on README.md
> +<<<<<<< HEAD
Done

2023-07-19 12:41 UTC, Nikita-Smirnov-Exactpro approved these changes

2023-08-15 17:16 UTC, merged